/*
#########################################################
## File Name: PossibleWords.java                       ##
## Description: Generating All Possible Words By Given ##
##				Word.								   ##
## Programmed By: FARHAN KHAN						   ##
#########################################################
*/
import java.util.*;
class PossibleWords{
	
//Checking For Possible Number Of Can Generated By Given String 	
	void PossibleWordGen(String word, int index, int len){
		
		if(index == len) //Checking For New Generated Word And Printing it
			System.out.println(word);
		else
		{
			for(int i=index; i<=len; i++)
			{
				word = swap(word,index,i);
				PossibleWordGen(word,index+1,len);	//Recursion Calling
				word = swap(word,index,i);
			}
		}
	}
	
//Method Responsible For Swapping	
	String swap(String word,int i,int j){
		char temp;
		char[] charArray = word.toCharArray();	//Converting String Into Array So That Swapping Can Be Performed 
		temp = charArray[i];
		charArray[i] = charArray[j];
		charArray[j] = temp;
		return String.valueOf(charArray); //Returning a String Object
	}
	
	public static void main(String[] args){
		int index = 0,len = 0;
		Scanner sc = new Scanner(System.in);
		PossibleWords obj = new PossibleWords();
		System.out.println("Enter A Word");
		String word = sc.next();
		len = word.length();
		obj.PossibleWordGen(word,index,len-1);
		}
}